### ISSUE TITLE
dotenv tests fail

### ISSUE THREAD

**Issue by Skgland** [casey/just#1879]
```sh
bennet@DESKTOP-RP6E64N:~/git/just$> cargo test
```

```log
<!-- snip -->
failures:

---- dotenv::can_set_dotenv_path_from_justfile stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"bar\n"

thread 'dotenv::can_set_dotenv_path_from_justfile' panicked at tests/test.rs:266:7:
Output mismatch.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- dotenv::filename_flag_overwrites_no_load stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"bar\n"

thread 'dotenv::filename_flag_overwrites_no_load' panicked at tests/test.rs:266:7:
Output mismatch.

---- dotenv::filename_resolves stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"bar\n"

thread 'dotenv::filename_resolves' panicked at tests/test.rs:266:7:
Output mismatch.

---- dotenv::program_argument_has_priority_for_dotenv_filename stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"baz\n"

thread 'dotenv::program_argument_has_priority_for_dotenv_filename' panicked at tests/test.rs:266:7:
Output mismatch.

---- dotenv::can_set_dotenv_filename_from_justfile stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"bar\n"

thread 'dotenv::can_set_dotenv_filename_from_justfile' panicked at tests/test.rs:266:7:
Output mismatch.

---- dotenv::path_resolves stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"bar\n"

thread 'dotenv::path_resolves' panicked at tests/test.rs:266:7:
Output mismatch.

---- dotenv::program_argument_has_priority_for_dotenv_path stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"baz\n"

thread 'dotenv::program_argument_has_priority_for_dotenv_path' panicked at tests/test.rs:266:7:
Output mismatch.

---- dotenv::path_flag_overwrites_no_load stdout ----
Bad stdout: Diff < left / right > :
<"DESKTOP-RP6E64N\n"
>"bar\n"

thread 'dotenv::path_flag_overwrites_no_load' panicked at tests/test.rs:266:7:
Output mismatch.


failures:
    dotenv::can_set_dotenv_filename_from_justfile
    dotenv::can_set_dotenv_path_from_justfile
    dotenv::filename_flag_overwrites_no_load
    dotenv::filename_resolves
    dotenv::path_flag_overwrites_no_load
    dotenv::path_resolves
    dotenv::program_argument_has_priority_for_dotenv_filename
    dotenv::program_argument_has_priority_for_dotenv_path

test result: FAILED. 645 passed; 8 failed; 7 ignored; 0 measured; 0 filtered out; finished in 0.82s

error: test failed, to rerun pass `--test integration`
```

```sh
$> cargo --version
cargo 1.75.0 (1d8b05cdd 2023-11-20)
$> rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
$> git branch -v
* master d1e2ef7 Install mdbook with cargo in CI workflow (#1877)
$> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

In WSL2 
```sh
$> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by Skgland** [comment]
```sh
$> export
<!-- snip -->
declare -x NAME="DESKTOP-RP6E64N"
<!-- snip -->
```

**Comment by Skgland** [comment]
It looks like the test maybe expect `NAME` to be unset?

**Comment by casey** [comment]
Whoops! Yeah we should definitely use a different variable name. I changed `NAME` to `JUST_TEST_VARIABLE` in #1882, which should hopefully fix this.
